import 'package:flutter/material.dart';

class AppColors {
  // Converted from Tailwind colors in main.html
  static const Color background = Color(0xFFFAF8FF);
  static const Color primaryContainer = Color(0xFF008378);
  static const Color onSecondaryContainer = Color(0xFF007353);
  static const Color outlineVariant = Color(0xFFBCC9C6);
  static const Color surfaceBright = Color(0xFFFAF8FF);
  static const Color surfaceVariant = Color(0xFFDAE2FD);
  static const Color tertiaryFixedDim = Color(0xFFFFB77D);
  static const Color surfaceContainerHigh = Color(0xFFE2E7FF);
  static const Color onPrimary = Color(0xFFFFFFFF);
  static const Color onSecondary = Color(0xFFFFFFFF);
  static const Color onSecondaryFixed = Color(0xFF002115);
  static const Color onTertiaryFixed = Color(0xFF2F1500);
  static const Color tertiary = Color(0xFF8D4B00);
  static const Color inverseSurface = Color(0xFF283044);
  static const Color secondary = Color(0xFF006C4E);
  static const Color inversePrimary = Color(0xFF6BD8CB);
  static const Color surfaceContainerLowest = Color(0xFFFFFFFF);
  static const Color onSurface = Color(0xFF131B2E);
  static const Color secondaryContainer = Color(0xFF97F5CC);
  static const Color outline = Color(0xFF6D7A77);
  static const Color surfaceContainerHighest = Color(0xFFDAE2FD);
  static const Color onError = Color(0xFFFFFFFF);
  static const Color secondaryFixedDim = Color(0xFF7BD8B1);
  static const Color onPrimaryFixed = Color(0xFF00201D);
  static const Color onTertiary = Color(0xFFFFFFFF);
  static const Color primaryFixedDim = Color(0xFF6BD8CB);
  static const Color surfaceTint = Color(0xFF006A61);
  static const Color surface = Color(0xFFFAF8FF);
  static const Color primaryFixed = Color(0xFF89F5E7);
  static const Color surfaceDim = Color(0xFFD2D9F4);
  static const Color onPrimaryFixedVariant = Color(0xFF005049);
  static const Color tertiaryContainer = Color(0xFFB15F00);
  static const Color onPrimaryContainer = Color(0xFFF4FFFC);
  static const Color onTertiaryFixedVariant = Color(0xFF6E3900);
  static const Color primary = Color(0xFF00685F);
  static const Color error = Color(0xFFBA1A1A);
  static const Color onSecondaryFixedVariant = Color(0xFF00513A);
  static const Color secondaryFixed = Color(0xFF97F5CC);
  static const Color onErrorContainer = Color(0xFF93000A);
  static const Color surfaceContainerLow = Color(0xFFF2F3FF);
  static const Color errorContainer = Color(0xFFFFDAD6);
  static const Color inverseOnSurface = Color(0xFFEEF0FF);
  static const Color onBackground = Color(0xFF131B2E);
  static const Color onTertiaryContainer = Color(0xFFFFFBFF);
  static const Color surfaceContainer = Color(0xFFEAEDFF);
  static const Color tertiaryFixed = Color(0xFFFFDCC3);
  static const Color onSurfaceVariant = Color(0xFF3D4947);
}
